// $COVERAGE-OFF$
package shapeless

import scala.Predef._

/** This object was generated by sbt-buildinfo. */
case object BuildInfo {
  /** The value is "2.3.10". */
  val version: String = "2.3.10"
  /** The value is "2.13.8". */
  val scalaVersion: String = "2.13.8"
  /** The value is scala.Some("69fd3d124777f7a389102c7bfacf6776e23c03a2"). */
  val gitHeadCommit: scala.Option[String] = scala.Some("69fd3d124777f7a389102c7bfacf6776e23c03a2")
  /** The value is "2022-11-10 20:25:07.869+0200". */
  val builtAtString: String = "2022-11-10 20:25:07.869+0200"
  /** The value is 1668104707869L. */
  val builtAtMillis: scala.Long = 1668104707869L
  override val toString: String = {
    "version: %s, scalaVersion: %s, gitHeadCommit: %s, builtAtString: %s, builtAtMillis: %s".format(
      version, scalaVersion, gitHeadCommit, builtAtString, builtAtMillis
    )
  }
}
// $COVERAGE-ON$
